@startnwdiag
nwdiag {
  group frontend {
    style = "dotted"
    web01;
    web02;
  }
  group backend {
    app01;
    app02;
  }
  network dmz {
    style = "dotted"
    web01; web02;
  }
  network internal {
    app01; app02;
  }
}
@endnwdiag
