' Deterministic Material cloud_download icon stub.
!include <material/common>

!procedure MA_CLOUD_DOWNLOAD($a, $b=cloud_download, $c=, $d=, $e=__PUML_MISSING__)
!if $e != __PUML_MISSING__
MaterialIcon($c, cloud_download, %unquote($e), "")
!else
MaterialIcon($a, cloud_download, %unquote($b), %unquote($c))
!endif
!endprocedure
