' Deterministic Material cloud_download icon stub.
!include <material/common>

!procedure MA_CLOUD_DOWNLOAD($alias, $label="cloud_download", $descr="")
MaterialIcon($alias, cloud_download, $label, $descr)
!endprocedure
