' Deterministic Material code icon stub.
!include <material/common>

!procedure MA_CODE($a, $b=code, $c=, $d=, $e=__PUML_MISSING__)
!if $e != __PUML_MISSING__
MaterialIcon($c, code, %unquote($e), "")
!else
MaterialIcon($a, code, %unquote($b), %unquote($c))
!endif
!endprocedure
