' Deterministic Material folder icon stub.
!include <material/common>

sprite $ma_folder [8x8/16] {
00000000
04444400
4FFFFF40
4F444F40
4FFFFF40
4F444F40
4FFFFF40
00000000
}

!procedure MA_FOLDER($a, $b=folder, $c=, $d=, $e=__PUML_MISSING__)
!if $e != __PUML_MISSING__
MaterialIcon($c, folder, %unquote($e), "")
!else
MaterialIcon($a, folder, %unquote($b), %unquote($c))
!endif
!endprocedure
