' Deterministic Material group icon stub.
!include <material/common>

!procedure MA_GROUP($a, $b=group, $c=, $d=, $e=__PUML_MISSING__)
!if $e != __PUML_MISSING__
MaterialIcon($c, group, %unquote($e), "")
!else
MaterialIcon($a, group, %unquote($b), %unquote($c))
!endif
!endprocedure
