' Deterministic Material integration_instructions icon stub.
!include <material/common>

!procedure MA_INTEGRATION_INSTRUCTIONS($a, $b=integration_instructions, $c=, $d=, $e=__PUML_MISSING__)
!if $e != __PUML_MISSING__
MaterialIcon($c, integration_instructions, %unquote($e), "")
!else
MaterialIcon($a, integration_instructions, %unquote($b), %unquote($c))
!endif
!endprocedure
