' Deterministic Material lock icon stub.
!include <material/common>

!procedure MA_LOCK($a, $b=lock, $c=, $d=, $e=__PUML_MISSING__)
!if $e != __PUML_MISSING__
MaterialIcon($c, lock, %unquote($e), "")
!else
MaterialIcon($a, lock, %unquote($b), %unquote($c))
!endif
!endprocedure
