' Deterministic Material network icon stub.
!include <material/common>

!procedure MA_NETWORK($a, $b=network, $c=, $d=, $e=__PUML_MISSING__)
!if $e != __PUML_MISSING__
MaterialIcon($c, network, %unquote($e), "")
!else
MaterialIcon($a, network, %unquote($b), %unquote($c))
!endif
!endprocedure
