' Deterministic Material smartphone icon stub.
!include <material/common>

!procedure MA_SMARTPHONE($a, $b=smartphone, $c=, $d=, $e=__PUML_MISSING__)
!if $e != __PUML_MISSING__
MaterialIcon($c, smartphone, %unquote($e), "")
!else
MaterialIcon($a, smartphone, %unquote($b), %unquote($c))
!endif
!endprocedure
