use super::completion::{CompletionItem, CompletionItemKind};

macro_rules! item {
    ($label:expr, $kind:expr, $detail:expr, $documentation:expr $(,)?) => {
        CompletionItem {
            label: $label,
            kind: $kind,
            detail: $detail,
            documentation: $documentation,
        }
    };
}

pub(super) fn extra_completion_specs() -> &'static [CompletionItem] {
    use CompletionItemKind::{Keyword, Operator};
    &[
        item!("!if", Keyword, "Preprocessor", "Start a preprocessor conditional block."),
        item!("!elseif", Keyword, "Preprocessor", "Start an alternate preprocessor conditional branch."),
        item!("!else", Keyword, "Preprocessor", "Start the fallback preprocessor conditional branch."),
        item!("!endif", Keyword, "Preprocessor", "End a preprocessor conditional block."),
        item!("!theme", Keyword, "Preprocessor", "Apply a built-in PlantUML theme."),
        item!("!import", Keyword, "Preprocessor", "Import a stdlib pack or local include namespace."),
        item!("while", Keyword, "Activity Diagram", "Start an activity while loop."),
        item!("endwhile", Keyword, "Activity Diagram", "End an activity while loop."),
        item!("repeat", Keyword, "Activity Diagram", "Start an activity repeat loop."),
        item!("repeat while", Keyword, "Activity Diagram", "Close an activity repeat loop with a condition."),
        item!("fork", Keyword, "Activity Diagram", "Start a parallel activity fork."),
        item!("fork again", Keyword, "Activity Diagram", "Start another branch inside an activity fork."),
        item!("end fork", Keyword, "Activity Diagram", "End an activity fork."),
        item!("partition", Keyword, "Activity Diagram", "Start an activity partition or swimlane."),
        item!("endpartition", Keyword, "Activity Diagram", "End an activity partition or swimlane."),
        item!("detach", Keyword, "Activity Diagram", "Detach the current activity flow."),
        item!("kill", Keyword, "Activity Diagram", "Terminate the current activity flow."),
        item!("--", Operator, "State Diagram", "State diagram transition separator."),
        item!("<|--", Operator, "Class Relation", "Generalization or inheritance relation."),
        item!("*--", Operator, "Class Relation", "Composition relation."),
        item!("o--", Operator, "Class Relation", "Aggregation relation."),
        item!("..|>", Operator, "Class Relation", "Dashed realization relation."),
        item!("..>", Operator, "Graph Relation", "Dashed dependency relation."),
        item!("component", Keyword, "Component Diagram", "Declare a component node."),
        item!("node", Keyword, "Deployment Diagram", "Declare a deployment node."),
        item!("artifact", Keyword, "Deployment Diagram", "Declare an artifact node."),
        item!("cloud", Keyword, "Deployment Diagram", "Declare a cloud node."),
        item!("folder", Keyword, "Deployment Diagram", "Declare a folder node."),
        item!("file", Keyword, "Deployment Diagram", "Declare a file node."),
        item!("rectangle", Keyword, "Component Diagram", "Declare a rectangular component or deployment node."),
        item!("frame", Keyword, "Deployment Diagram", "Declare a frame node."),
        item!("storage", Keyword, "Deployment Diagram", "Declare a storage node."),
        item!("stack", Keyword, "Deployment Diagram", "Declare a stack node."),
        item!("agent", Keyword, "Deployment Diagram", "Declare an agent node."),
        item!("person", Keyword, "Deployment Diagram", "Declare a person node."),
        item!("process", Keyword, "Deployment Diagram", "Declare a process node."),
        item!("container", Keyword, "Deployment Diagram", "Declare a container node."),
        item!("hexagon", Keyword, "Deployment Diagram", "Declare a hexagon node."),
        item!("label", Keyword, "Deployment Diagram", "Declare a label node."),
        item!("c4 person", Keyword, "C4 Diagram", "Declare a C4 person element."),
        item!("c4 system", Keyword, "C4 Diagram", "Declare a C4 system element."),
        item!("c4 component", Keyword, "C4 Diagram", "Declare a C4 component element."),
        item!("ArrowColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence, class."),
        item!("BackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: most rendered families."),
        item!("DefaultFontName", Keyword, "Skinparam", "Supported skinparam. Value type: font name. Families: sequence."),
        item!("DefaultFontSize", Keyword, "Skinparam", "Supported skinparam. Value type: integer pixels. Families: sequence."),
        item!("DefaultTextAlignment", Keyword, "Skinparam", "Supported skinparam. Value type: left, center, right. Families: sequence."),
        item!("RoundCorner", Keyword, "Skinparam", "Supported skinparam. Value type: integer pixels. Families: sequence, mindmap, wbs, salt."),
        item!("shadowing", Keyword, "Skinparam", "Supported skinparam. Value type: boolean. Families: sequence, ditaa."),
        item!("monochrome", Keyword, "Skinparam", "Supported skinparam. Value type: true, false, reverse. Families: sequence, class."),
        item!("handwritten", Keyword, "Skinparam", "Supported skinparam. Value type: boolean. Families: sequence."),
        item!("sepia", Keyword, "Skinparam", "Supported skinparam. Value type: boolean. Families: sequence."),
        item!("maxMessageSize", Keyword, "Skinparam", "Supported skinparam. Value type: integer pixels. Families: sequence."),
        item!("sequenceFootbox", Keyword, "Skinparam", "Supported skinparam. Value type: show or hide. Families: sequence."),
        item!("footbox", Keyword, "Skinparam", "Supported skinparam. Value type: show or hide. Families: sequence."),
        item!("sequenceMessageAlign", Keyword, "Skinparam", "Supported skinparam. Value type: left, center, right, direction, reverseDirection. Families: sequence."),
        item!("responseMessageBelowArrow", Keyword, "Skinparam", "Supported skinparam. Value type: boolean. Families: sequence."),
        item!("lifelineStyle", Keyword, "Skinparam", "Supported skinparam. Value type: solid or nosolid. Families: sequence."),
        item!("lifelineThickness", Keyword, "Skinparam", "Supported skinparam. Value type: integer pixels. Families: sequence."),
        item!("ParticipantBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("ParticipantBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("ParticipantFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("LifelineBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("MessageLineColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("NoteBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("NoteBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("GroupBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("GroupBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("GroupHeaderFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("GroupHeaderFontStyle", Keyword, "Skinparam", "Supported skinparam. Value type: plain, bold, italic, underline. Families: sequence."),
        item!("ReferenceBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("ReferenceBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: sequence."),
        item!("classBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: class."),
        item!("classBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: class."),
        item!("classHeaderBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: class."),
        item!("classAttributeFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: class."),
        item!("classFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: class."),
        item!("classArrowColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: class."),
        item!("classFontSize", Keyword, "Skinparam", "Supported skinparam. Value type: integer pixels. Families: class."),
        item!("classFontName", Keyword, "Skinparam", "Supported skinparam. Value type: font name. Families: class."),
        item!("actorStyle", Keyword, "Skinparam", "Supported skinparam. Value type: stickman or awesome. Families: class/usecase."),
        item!("StateBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: state."),
        item!("StateBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: state."),
        item!("StateArrowColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: state."),
        item!("StateStartColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: state."),
        item!("StateFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: state."),
        item!("StateFontSize", Keyword, "Skinparam", "Supported skinparam. Value type: integer pixels. Families: state."),
        item!("ActivityBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: activity."),
        item!("ActivityBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: activity."),
        item!("ActivityDiamondBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: activity."),
        item!("ActivityDiamondBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: activity."),
        item!("ActivityArrowColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: activity."),
        item!("ActivityFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: activity."),
        item!("ComponentBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: component."),
        item!("ComponentBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: component."),
        item!("ComponentInterfaceColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: component."),
        item!("ComponentFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: component."),
        item!("ComponentArrowColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: component."),
        item!("componentStyle", Keyword, "Skinparam", "Supported skinparam. Value type: uml1, uml2, rectangle. Families: component."),
        item!("TimingBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: timing."),
        item!("TimingAxisColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: timing."),
        item!("TimingGridColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: timing."),
        item!("TimingSignalBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: timing."),
        item!("TimingSignalBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: timing."),
        item!("TimingArrowColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: timing."),
        item!("TimingFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: timing."),
        item!("ChartBackgroundColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: chart."),
        item!("ChartAxisColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: chart."),
        item!("ChartGridColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: chart."),
        item!("ChartSeriesColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: chart."),
        item!("ChartBarColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: chart."),
        item!("ChartLineColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: chart."),
        item!("ChartPieBorderColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: chart."),
        item!("ChartFontColor", Keyword, "Skinparam", "Supported skinparam. Value type: color. Families: chart."),
    ]
}

pub(super) fn resolve_extra_completion_item(label: &str) -> Option<CompletionItem> {
    extra_completion_specs()
        .iter()
        .find(|entry| entry.label.eq_ignore_ascii_case(label))
        .cloned()
}
