' Merged AWS EC2 compatibility surface.

!procedure EC2($alias, $label="", $description="")
object $label as $alias <<aws-ec2>>
!endprocedure

!procedure EC2Spotfleet($alias, $label, $description="")
object $label as $alias <<aws-ec2-spotfleet>>
!endprocedure
