flowchart TD
    R[Rectangle]
    RO(Rounded)
    CI((Circle))
    RH{Rhombus}
    SU[[Subroutine]]
    DB[(Database)]
    HX{{Hexagon}}
    AS>Asymmetric]
    R --> RO
    RO --> CI
    CI --> RH
    RH --> SU
    SU --> DB
    DB --> HX
    HX --> AS
