@startuml
abstract class Shape {
  color: String
  {abstract} area(): Float
  {abstract} perimeter(): Float
}
interface Drawable {
  draw(): void
}
class Circle {
  radius: Float
  area(): Float
  perimeter(): Float
}
class Rectangle {
  width: Float
  height: Float
  area(): Float
}
Shape <|-- Circle
Shape <|-- Rectangle
Drawable <|.. Circle
@enduml
