@startuml
title Abstract and Interface Pattern
abstract class Shape {
  {abstract} +area(): double
  {abstract} +perimeter(): double
}
interface Drawable {
  +draw(): void
}
interface Resizable {
  +resize(f: double): void
}
class Circle {
  -radius: double
  +area(): double
  +perimeter(): double
}
Shape <|-- Circle
Drawable <|.. Circle
Resizable <|.. Circle
@enduml
