@startuml
title Collection Hierarchy
interface Iterable {
  +iterator()
}
interface Collection {
  +add(e): boolean
  +size(): int
}
interface List {
  +get(i: int)
}
class ArrayList {
  +add(e): boolean
  +get(i: int)
  +size(): int
}
Iterable <|.. Collection
Collection <|.. List
List <|.. ArrayList
@enduml
