@startuml
title Composite Pattern
class FileSystemNode {
  +name(): String
  +size(): long
}
class File {
  -name: String
  +name(): String
  +size(): long
}
class Directory {
  -name: String
  -children: List
  +add(node): void
  +name(): String
  +size(): long
}
File <|-- FileSystemNode
Directory <|-- FileSystemNode
Directory *-- FileSystemNode
@enduml
