@startuml
title Command Pattern
class Command {
  +execute(): void
  +undo(): void
}
class Invoker {
  -history: Stack
  +execute(cmd: Command): void
  +undo(): void
}
class Receiver {
  +action(): void
}
class ConcreteCommand {
  -receiver: Receiver
  +execute(): void
  +undo(): void
}
ConcreteCommand <|-- Command
Invoker o-- Command
ConcreteCommand --> Receiver
@enduml
