#!/usr/bin/env python3
from pathlib import Path
import re
import sys

if len(sys.argv) != 3:
    print(
        "usage: import_material_icons.py MATERIAL_DESIGN_ICONS_SRC_DIR OUT_RS",
        file=sys.stderr,
    )
    raise SystemExit(2)

src_dir = Path(sys.argv[1])
out = Path(sys.argv[2])
icons = {}
for path in sorted(src_dir.glob("*/*/materialicons/24px.svg")):
    name = path.parents[1].name
    raw = path.read_text(encoding="utf-8").strip()
    raw = re.sub(r">\s+<", "><", raw)
    raw = re.sub(r"\s+", " ", raw)
    raw = raw.replace(" />", "/>")
    if name in icons:
        print(f"duplicate material icon name: {name}", file=sys.stderr)
        raise SystemExit(1)
    icons[name] = raw

lines = [
    "// @generated by scripts/import_material_icons.py; do not edit by hand.",
    "// Source: Google Material Design Icons classic filled 24px SVGs.",
    "// Upstream: https://github.com/google/material-design-icons/tree/master/src.",
    "// License: Apache-2.0. See THIRD_PARTY_NOTICES.md.",
    "",
    "pub(crate) const MATERIAL_ICONS_SVG: &[(&str, &str)] = &[",
]
for name, svg in sorted(icons.items()):
    lines.append(f"    (\"{name}\", r#\"{svg}\"#),")
lines.append("];")
lines.append("")
out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {len(icons)} icons to {out}")
