#!/usr/bin/env python3
from pathlib import Path
import re
import sys

if len(sys.argv) != 3:
    print("usage: import_openiconic.py OPEN_ICONIC_SVG_DIR OUT_RS", file=sys.stderr)
    raise SystemExit(2)

svg_dir = Path(sys.argv[1])
out = Path(sys.argv[2])
icons = []
for path in sorted(svg_dir.glob("*.svg")):
    name = path.stem
    raw = path.read_text(encoding="utf-8").strip()
    raw = re.sub(r">\s+<", "><", raw)
    raw = re.sub(r"\s+", " ", raw)
    raw = raw.replace(" />", "/>")
    icons.append((name, raw))

lines = [
    "// @generated by scripts/import_openiconic.py; do not edit by hand.",
    "// Source: Open Iconic SVG icons from https://github.com/iconic/open-iconic.",
    "// License: MIT, Copyright (c) 2014 Waybury. See THIRD_PARTY_NOTICES.md.",
    "",
    "pub(crate) const OPENICONIC_SVG: &[(&str, &str)] = &[",
]
for name, svg in icons:
    lines.append(f"    (\"{name}\", r#\"{svg}\"#),")
lines.append("];")
lines.append("")
out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {len(icons)} icons to {out}")
