#!/usr/bin/env python3
from pathlib import Path
import re
import sys

if len(sys.argv) not in (3, 4):
    print(
        "usage: import_bootstrap_icons.py BOOTSTRAP_ICONS_SVG_DIR OUT_RS [VERSION]",
        file=sys.stderr,
    )
    raise SystemExit(2)

svg_dir = Path(sys.argv[1])
out = Path(sys.argv[2])
version = sys.argv[3] if len(sys.argv) == 4 else "unknown"

icons = []
for path in sorted(svg_dir.glob("*.svg")):
    name = path.stem
    raw = path.read_text(encoding="utf-8").strip()
    raw = re.sub(r">\s+<", "><", raw)
    raw = re.sub(r"\s+", " ", raw)
    raw = raw.replace(" />", "/>")
    raw = re.sub(r'\sfill="currentColor"', "", raw)
    icons.append((name, raw))

lines = [
    "// @generated by scripts/import_bootstrap_icons.py; do not edit by hand.",
    f"// Source: Bootstrap Icons SVG icons v{version} from https://github.com/twbs/icons.",
    "// License: MIT, Copyright (c) 2019-2024 The Bootstrap Authors. See THIRD_PARTY_NOTICES.md.",
    "",
    "pub(crate) const BOOTSTRAP_ICONS_SVG: &[(&str, &str)] = &[",
]
for name, svg in icons:
    lines.append(f"    (\"{name}\", r#\"{svg}\"#),")
lines.append("];")
lines.append("")
out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {len(icons)} icons to {out}")
