' Deterministic tupadr3 devicons grafana stub.
!include <tupadr3/common>

!procedure DEV_GRAFANA($alias, $label="grafana", $descr="")
FontAwesomeIcon($alias, devicons_grafana, $label, $descr)
!endprocedure
