@startditaa
' Ditaa (ASCII art to diagram) not yet supported by this parser
+-------+   +--------+
| Client|-->| Server |
+-------+   +--------+
                |
           +--------+
           |   DB   |
           +--------+
@endditaa
